version: '3'
services:
  gubal-db:
    image: mariadb
    container_name: gubal-db
    environment:
      TZ: Europe/Helsinki  
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PWD}
    ports:
      - ${MYSQL_PORT}:3306
